export const period = [{value: '2019', label: '2019'},
                      {value: '2018', label: '2018'},
                      {value: '2017', label: '2017'},
                      {value: '2016', label: '2016'}]

export const state = [{value: '12', label: 'Acre'},
                      {value: '27', label: 'Alagoas'},
                      {value: '16', label: 'Amapá'},
                      {value: '13', label: 'Amazonas'},
                      {value: '29', label: 'Bahia'},
                      {value: '23', label: 'Ceará'},
                      {value: '53', label: 'Distrito Federal'},
                      {value: '32', label: 'Espírito Santo'},
                      {value: '52', label: 'Goiás'},
                      {value: '21', label: 'Maranhão'},
                      {value: '51', label: 'Mato Grosso'},
                      {value: '50', label: 'Mato Grosso do Sul'},
                      {value: '31', label: 'Minas Gerais'},
                      {value: '15', label: 'Pará'},
                      {value: '25', label: 'Paraíba'},
                      {value: '41', label: 'Paraná'},
                      {value: '22', label: 'Piauí'},
                      {value: '33', label: 'Rio de Janeiro'},
                      {value: '24', label: 'Rio Grande do Norte'},
                      {value: '43', label: 'Rio Grande do Sul'},
                      {value: '11', label: 'Rondônia'},
                      {value: '14', label: 'Roraima'},
                      {value: '42', label: 'Santa Catarina'},
                      {value: '35', label: 'São Paulo'},
                      {value: '28', label: 'Sergipe'},
                      {value: '17', label: 'Tocantins'}]